services:
  customer-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT_DIR: CustomerService
    image: customer-service:1.0.0
    container_name: customer-service
    ports:
      - "8081:8081"
    restart:
      always

  my-prometheus:
    image: prom/prometheus
    container_name: my-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  tempo-init:
    image: alpine:latest
    user: root
    volumes:
      - tempo-data:/tmp/tempo
    command: chown -R 10001:10001 /tmp/tempo

  my-tempo:
    image: grafana/tempo:latest
    container_name: my-tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./docker/tempo/tempo.yaml:/etc/tempo.yaml:ro
      - tempo-data:/tmp/tempo
    ports:
      - "3200:3200" # Tempo
      - "9411:9411" # zipkin
    depends_on:
      - tempo-init

  my-loki:
    image: grafana/loki:main
    container_name: my-loki
    command: [ "-config.file=/etc/loki/local-config.yaml" ]
    ports:
      - "3100:3100"

  my-grafana:
    image: grafana/grafana
    container_name: my-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./docker/grafana:/etc/grafana/provisioning/datasources:ro
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password

volumes:
  tempo-data:
